<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <IsAotCompatible>true</IsAotCompatible>

        <Version>12.0.2</Version>

        <Copyright>Copyright 2022-$([System.DateTime]::Now.ToString(`yyyy`)) &#169; The Tabalonia Project</Copyright>
        <PackageId>Caly.Tabalonia</PackageId>
        <PackageProjectUrl>https://github.com/CalyPdf/Caly.Tabalonia</PackageProjectUrl>
        <RepositoryUrl>https://github.com/CalyPdf/Caly.Tabalonia</RepositoryUrl>
        <PackageTags>Tab Control, Draggable, Avalonia, AvaloniaUI, Caly, CalyPdf</PackageTags>
        <Description>For use in Caly Pdf: Tab Control with draggable tabs for Avalonia</Description>
        <PackageIcon>Icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes>See https://github.com/CalyPdf/Caly.Tabalonia/blob/main/CHANGELOG.md</PackageReleaseNotes>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <PropertyGroup Label="Avalonia">
        <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <PropertyGroup Label="SourceLink">
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    </ItemGroup>

    <ItemGroup Label="PackageIcon">
        <None Include="..\Icon.png" Pack="true" Visible="false" PackagePath="" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" Visible="false" PackagePath="\" />
        <None Include="..\LICENSE" Pack="true" Visible="false" PackagePath="" />
    </ItemGroup>

</Project>
